
experiment_name: baseline

data:
  dataset: USC-annot-16 # options: USC-annot-16 | USC-TIMIT
  root: data/USC-annot-16
  phonemic_table: data/Phonemic_Table.xlsx
  classification_task: voicing # manner | place | voicing, set to "" or None for multi-task
  untrained_subjects: # list of subjects to hold out for testing
  untrained_tasks: # list of tasks to hold out for testing
  test_ratio: 0.1
  n_splits: 5
  fps: 15
  audio_sample_rate: 16000
  audio_window_sec: 0.06667
  seed: 42

train:
  epochs: 30
  batch_size: 32
  lr: 0.0001
  weight_decay: 0.0005
  num_workers: 4
  device: cuda
  data_augment: false  # when true, enables RandomAffine on images + random time shift on images & audio

model:
  image_encoder:
    type: monai_vit
    pretrained: false
    img_size: 128
    image_channels: 3
    patch_size: 16
    hidden_size: 768
    mlp_dim: 3072
    num_layers: 12
    num_heads: 12
    dropout_rate: 0.1

  backbone:
    type: wav2vec2
    name: facebook/wav2vec2-base-960h
    freeze: true
    hidden_size: 768
    target_time_steps: 31

  projection:
    visual_tokens: 65
    target_tokens: 31
    hidden_size: 768

  classifier:
    input_dim: 23808
    dropout: 0.1

loss:
  contrast_loss: cosine # options: cosine | infonce
  lambda: 0.1
  use_class_weights: true



paths:
  checkpoint_dir: ./checkpoints
  log_dir: ./logs
