experiment_name: img_baseline

data:
  dataset: USC-annot-16
  root: data/USC-annot-16
  phonemic_table: data/Phonemic_Table.xlsx
  classification_task:   # manner | place | voicing | vowel_backness, set to "" for multi-task
  unseen_speakers: [sub023, sub028, sub043, sub061] # list of unseen speakers for test set
  unseen_task_types: [vcv]  # list of unseen task types for test set
  test_ratio: 0.1
  n_splits: 5
  fps: 15
  audio_sample_rate: 16000
  audio_window_sec: 0.06667
  seed: 42

model:
  image_encoder:
    img_size: 128
    patch_size: 16
    hidden_size: 768
    mlp_dim: 3072
    num_layers: 12
    num_heads: 12
    dropout: 0.1
  classifier:
    clf_hidden_dim: 256

train:
  epochs: 30
  batch_size: 32
  num_workers: 4
  lr_encoder: 1.0e-4
  lr_classifier: 1.0e-4
  weight_decay: 0.0005
  grad_clip: 0.5
  data_augment: false

loss:
  lambda_contrast: 0.0
  contrast_loss_name: null
  contrast_loss_kwargs: null
  use_class_weights: true
  bce_pos_weight: false
  lambda_manner: 1.0
  lambda_place: 1.0
  lambda_voicing: 1.0
  lambda_vowel_backness: 1.0

paths:
  checkpoint_dir: ./checkpoints
  log_dir: ./logs
